spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mciet
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: hunil@3751
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
google:
  clientId: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

cloud:
  aws:
    credentials:
      access-key: AKIAVKTZVOBKYBCQCMOR
      secret-key: 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
    s3:
      bucket: mciet-bucket
      base-url: https://mciet-bucket.s3.ap-northeast-2.amazonaws.com
    region:
      static: ap-northeast-2
    stack:
      auto: false
